-- Los usuarios ya no se siembran con un id aleatorio: usuarios.id debe
-- coincidir exactamente con el id de su cuenta en auth.users (Supabase Auth).
--
-- Pasos para dar de alta a Jaime, Laura y Reyes:
--   1. Crea sus cuentas de Auth (dashboard: Authentication → Users → Invite
--      user), opcionalmente con { "nombre": "…" } en el metadata.
--   2. El trigger `handle_new_user` crea su fila en `usuarios`. Desde 0008
--      toda cuenta nace 'comercial': el rol NUNCA se toma del metadata (lo
--      controla quien se registra).
--   3. Para hacer admin a alguien, en el SQL Editor:
--      update usuarios set rol = 'admin' where email = '…';
